#%RAML 1.0
title: api-mule4-poc

/poc/v1:
  get:
    responses:
     200:
        body:
          application/json:
            example: "POC V1"

/poc/v2:
  get:
    responses:
     200:
        body:
          application/json:
            example: "POC V2"
      